INSERT INTO USERS (ROLE,EMAIL,NAME,PASSWORD) VALUES ('ROLE_USER','adrian@gmail.com','Adrian','$2a$10$9usQnVHw.319Dfyt6WthN.PFM8wsbQTQ30sw6KqX29xK5gUX/.aAu');
INSERT INTO USERS (ROLE,EMAIL,NAME,PASSWORD) VALUES ('ROLE_ADMIN','pepe@gmail.com','Pepe','$2a$10$9usQnVHw.319Dfyt6WthN.PFM8wsbQTQ30sw6KqX29xK5gUX/.aAu');
INSERT INTO USERS (ROLE,EMAIL,NAME,PASSWORD) VALUES ('ROLE_USER','alfredo@gmail.com','Alfredo','$2a$10$9usQnVHw.319Dfyt6WthN.PFM8wsbQTQ30sw6KqX29xK5gUX/.aAu');
